package main

import (
	"io/ioutil"
	"log"
	"net/http"
	"net/http/httputil"
)

//https://oauthplay.azurewebsites.net/でトークンを取る。
//まずはそこから始めよう。
func main() {
	url := "https://graph.microsoft.com/v1.0/me"
	req, _ := http.NewRequest("GET", url, nil)
	req.Header.Set("Authorization", "eyJ0eXAiOiJKV1QiLCJub25jZSI6IkFRQUJBQUFBQUFCSGg0a21TX2FLVDVYcmp6eFJBdEh6Y09hUVNfMmw3cWJ4OVJVZzREWVpoalhWMG5kMVBidU9sUjFXeko5dkVjakdndHRiRTZqMk9kcUphTHJ1a1RCWmdyT2ctRC1rdW9BRXdQcE1QUlV3VkNBQSIsImFsZyI6IlJTMjU2IiwieDV0IjoiMktWY3V6cUFpZE9McVdTYW9sN3dnRlJHQ1lvIiwia2lkIjoiMktWY3V6cUFpZE9McVdTYW9sN3dnRlJHQ1lvIn0.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8yY2ZlZTlhMS0yYzZiLTQzMjAtODZlNy05MWI5MzVjY2I1ZTgvIiwiaWF0IjoxNTA4Mzg4MzQ3LCJuYmYiOjE1MDgzODgzNDcsImV4cCI6MTUwODM5MjI0NywiYWNyIjoiMSIsImFpbyI6IkFTUUEyLzhHQUFBQVdRNUdQSXBIdE5tOU5xaXVqd004d1FVekErOXIrSmYxdWJBcjZXUWJ4N1U9IiwiYW1yIjpbInB3ZCJdLCJhcHBfZGlzcGxheW5hbWUiOiJ0ZXN0LW91dGxvb2stYXBpIiwiYXBwaWQiOiIwYTc3YzFkYS1iNGQwLTQ4ZDMtYTcxZS0wNzAwNWRkNWM0MjkiLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6IumHkeajriIsImdpdmVuX25hbWUiOiLpm4TlpKciLCJpcGFkZHIiOiIyMTguMjI1LjgzLjk3IiwibmFtZSI6IumHkeajriDpm4TlpKciLCJvaWQiOiI4MjNkYmRkYS04Yzg4LTRjYTYtODRlYi1mNjc3ZTIwZWJkNjEiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMTI3MzY4NDk2OS0xMzU2MzAyMDUwLTMyMjgwODY5NzQtMTE4NyIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMDAwMEExMTI5OUQyIiwic2NwIjoiQ2FsZW5kYXJzLlJlYWQgQ29udGFjdHMuUmVhZCBNYWlsLlJlYWQgVXNlci5SZWFkIiwic3ViIjoiOFFCZlNrblhOeE9oMHZmZHF2akNINkQ0bzBjeFZJeDg1aTh1REdSOU0wUSIsInRpZCI6IjJjZmVlOWExLTJjNmItNDMyMC04NmU3LTkxYjkzNWNjYjVlOCIsInVuaXF1ZV9uYW1lIjoia2FuYW1vcmlAdHN1bmFndW5ldC5jb20iLCJ1cG4iOiJrYW5hbW9yaUB0c3VuYWd1bmV0LmNvbSIsInV0aSI6Ik1lVVUxNUdCYjBlZFhLVU4tb0JKQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjI5MjMyY2RmLTkzMjMtNDJmZC1hZGUyLTFkMDk3YWYzZTRkZSIsImZlOTMwYmU3LTVlNjItNDdkYi05MWFmLTk4YzNhNDlhMzhiMSIsImYwMjNmZDgxLWE2MzctNGI1Ni05NWZkLTc5MWFjMDIyNjAzMyIsIjcyOTgyN2UzLTljMTQtNDlmNy1iYjFiLTk2MDhmMTU2YmJiOCJdfQ.G1MBqqZofv5UxRqpCMzxZbdu_QdAvt-QuPtcjfxpLM6KC7Q5uuU9KLcI3YkV0kHy9T671ISO9UPlzme2b2p8b830uEK--YTwzycD2zK5BMGlxoMH7KDlLqDokSmaely56DV0uOXxvSQx6BRCB8Y4mTfgrcx76sW_B6LHACJJYMuNPEHv6yL1y_swSXLcRe0ctQF6ysb57O-YGQf2biV0PzrUeyUQ5Uou2xPV1YHRYM0KDoD4kR6Roo8KNvHkfiTV6s4-SUjttKUUmFXU5INhdp1BMKykZLimsf3RTm-BmhFHnwSmN_VpxkQ9TFbTnzIXHqvUi6U7tohmEG5m_0BNiQ")

	log.Printf("req1 : %s\n", req)

	dump, _ := httputil.DumpRequestOut(req, true)
	log.Printf("req set header : %s\n", dump)

	client := new(http.Client)
	resp, _ := client.Do(req)
	defer resp.Body.Close()

	dumpResp, _ := httputil.DumpResponse(resp, true)
	log.Printf("resp : %s\n", dumpResp)

	byteArray, _ := ioutil.ReadAll(resp.Body)
	log.Println(string(byteArray))
}
